application:
  name: 'default-weather'

worker:
  id: 'default-weather'
  host: '127.0.0.1'
  environment: 'local'
  environment-sequence: 'local'

nacos:
  serverAddr: 127.0.0.1:8848

server:
  http:
    port: 8081