fel:
  openai:
    api-base: 'https://api.siliconflow.cn/v1'
    api-key: 'sk-izfmuercmorlnwqtzdkpgskmdjlnjdtheaaypyrfyetkcsaf'
example:
  model: 'Qwen/Qwen2.5-7B-Instruct'


okhttp:
  config-client:
    cache:
      max-size: 20